Test (#14)
* test: 브랜치 전략 테스트

test -> staging

* refactor: badrequest로 변경 (#3)

* Hongkikii patch 2 (#7)

* production으로 가자 (#4) (#5)

* test: 브랜치 전략 테스트

test -> staging

* refactor: badrequest로 변경

---------

Co-authored-by: mimi <110226866+hongkikii@users.noreply.github.com>

* Update ci-cd.yml (#6)

* Create ci-cd-test.yml

---------

Co-authored-by: JongHyeon Choi <61353820+JHyeonC@users.noreply.github.com>

* Rename ci-cd-test to ci-cd-test.yml (#8)

* Create ci-cd-staging.yml (#9)

* Hongkikii patch 5 (#11)

* production으로 가자 (#4) (#5)

* test: 브랜치 전략 테스트

test -> staging

* refactor: badrequest로 변경

---------

Co-authored-by: mimi <110226866+hongkikii@users.noreply.github.com>

* Update ci-cd.yml (#6)

* Test (#10)

* test: 브랜치 전략 테스트

test -> staging

* refactor: badrequest로 변경 (#3)

* Hongkikii patch 2 (#7)

* production으로 가자 (#4) (#5)

* test: 브랜치 전략 테스트

test -> staging

* refactor: badrequest로 변경

---------

Co-authored-by: mimi <110226866+hongkikii@users.noreply.github.com>

* Update ci-cd.yml (#6)

* Create ci-cd-test.yml

---------

Co-authored-by: JongHyeon Choi <61353820+JHyeonC@users.noreply.github.com>

* Rename ci-cd-test to ci-cd-test.yml (#8)

* Create ci-cd-staging.yml (#9)

---------

Co-authored-by: JongHyeon Choi <61353820+JHyeonC@users.noreply.github.com>

* Update ci-cd-staging.yml

---------

Co-authored-by: JongHyeon Choi <61353820+JHyeonC@users.noreply.github.com>

* fix: 코드변경 (#12)

* fix: log level 변경 (#13)

---------

Co-authored-by: mimi <110226866+hongkikii@users.noreply.github.com>

diff --git a/.github/workflows/ci-cd-staging.yml b/.github/workflows/ci-cd-staging.yml
--- a/.github/workflows/ci-cd-staging.yml
+++ b/.github/workflows/ci-cd-staging.yml
@@ -3,96 +3,30 @@ name: CI CD
 on:
   push:
     branches:
-      - production
+      - staging
 
 env:
   EC2_USERNAME: ubuntu
   AWS_REGION: ap-northeast-2
-  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
+  ECR_REPOSITORY: ${{ secrets.AWS_ECR_STAGING_REPOSITORY }}
   EKS_CLUSTER: ${{ secrets.AWS_CLUSTER_NAME }}
   IMAGE_TAG: ${{ github.sha }}
 
 jobs:
-  build:
-    name: Build and Analyze
+  check-source-branch:
+    name: Validate PR Source Branch
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: corretto
-          
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-
-      - name: Cache Gradle packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-          restore-keys: ${{ runner.os }}-gradle
-
-      - name: Grant execute permission for gradlew
-        run: chmod +x ./gradlew
-
-      - name: Build and Analyze
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: ./gradlew build sonar --info
-
-      - name: Check SonarCloud Quality Gate
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
+      - name: Check if PR is from 'test' branch
+        if: github.event.pull_request.head.ref != 'test'
         run: |
-          sleep 20
-          RESULT=$(curl -u "${SONAR_TOKEN}:" \
-            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=mju-ai-pro_ai-pro-server")
-          STATUS=$(echo $RESULT | jq -r '.projectStatus.status')
-          echo "Quality Gate Status: $STATUS"
-          
-          if [ "$STATUS" = "OK" ]; then
-            echo "Quality Gate 통과"
-          else
-            echo "Quality Gate 통과 실패"
-            MESSAGE="❗ 배포 중 품질 게이트를 통과하지 못했습니다.: ${{ github.repository }} (${{ github.ref }})"
-            DETAILS="자세한 내용: https://sonarcloud.io/dashboard?id=mju-ai-pro_ai-pro-server"
-            
-            DATA='{
-              "embeds": [
-                {
-                  "title": "품질 게이트 통과 실패",
-                  "description": "'"${MESSAGE}"'\n\n'"${DETAILS}"'",
-                  "color": 16711680,
-                  "footer": {
-                    "text": "알림"
-                  }
-                }
-              ]
-            }'
-
-            curl -X POST -H 'Content-type:application/json' -d "$DATA" ${{ secrets.DISCORD_WEBHOOK_URL }}
-            
-            exit 1
-          fi
-
+          echo "ERROR: Only PRs from the 'test' branch are allowed to merge into 'staging'."
+          exit 1
+  
   deploy:
-    name: Deploy to AWS EC2
+    name: Deploy to AWS K8S
     runs-on: ubuntu-latest
-    needs: build
-    if: success()
-    
+    needs: check-source-branch
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
@@ -132,27 +66,27 @@ jobs:
       - name: Create Kubernetes Secrets
         run: |
           kubectl create secret generic db-config --dry-run=client -o yaml \
-            --from-literal=db-url="${{ secrets.DB_URL }}" \
-            --from-literal=db-username="${{ secrets.DB_USERNAME }}" \
-            --from-literal=db-password="${{ secrets.DB_PASSWORD }}" | kubectl apply -f -
+            --from-literal=db-url="${{ secrets.STAGING_DB_URL }}" \
+            --from-literal=db-username="${{ secrets.STAGING_DB_USERNAME }}" \
+            --from-literal=db-password="${{ secrets.STAGING_DB_PASSWORD }}" | kubectl apply -f -
 
           kubectl create secret generic app-config --dry-run=client -o yaml \
             --from-literal=jwt-secret="${{ secrets.JWT_SECRET }}" \
-            --from-literal=ai-url="${{ secrets.AI_URL }}" \
-            --from-literal=ai-summary="${{ secrets.AI_SUMMARY }}" | kubectl apply -f -
+            --from-literal=ai-url="${{ secrets.STAGING_AI_URL }}" \
+            --from-literal=ai-summary="${{ secrets.STAGING_AI_SUMMARY }}" | kubectl apply -f -
 
       - name: Deploy initial service and blue deployment if not exists
         run: |
-          if ! kubectl get service ai-pro-server-service &>/dev/null; then
+          if ! kubectl get service ai-pro-staging-service &>/dev/null; then
             echo "Creating initial service..."
             cat <<'EOF' | kubectl apply -f -
             apiVersion: v1
             kind: Service
             metadata:
-             name: ai-pro-server-service
+             name: ai-pro-staging-service
             spec:
              selector:
-               app: ai-pro-server
+               app: ai-pro-staging
                version: blue
              ports:
                - protocol: TCP
@@ -166,37 +100,37 @@ jobs:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
-            name: ai-pro-server-blue
+            name: ai-pro-staging-blue
           spec:
             replicas: 2
             selector:
               matchLabels:
-                app: ai-pro-server
+                app: ai-pro-staging
                 version: blue
             template:
               metadata:
                 labels:
-                  app: ai-pro-server
+                  app: ai-pro-staging
                   version: blue
               spec:
                 containers:
-                  - name: ai-pro-server
+                  - name: ai-pro-staging
                     image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
                     imagePullPolicy: Always
                     ports:
                       - containerPort: 8080
                     env:
-                    - name: DB_URL
+                    - name: STAGING_DB_URL
                       valueFrom:
                         secretKeyRef:
                           key: db-url
                           name: db-config
-                    - name: DB_USERNAME
+                    - name: STAGING_DB_USERNAME
                       valueFrom:
                         secretKeyRef:
                           key: db-username
                           name: db-config
-                    - name: DB_PASSWORD
+                    - name: STAGING_DB_PASSWORD
                       valueFrom:
                         secretKeyRef:
                           key: db-password
@@ -206,12 +140,12 @@ jobs:
                         secretKeyRef:
                           key: jwt-secret
                           name: app-config
-                    - name: AI_URL
+                    - name: STAGING_AI_URL
                       valueFrom:
                         secretKeyRef:
                           key: ai-url
                           name: app-config
-                    - name: AI_SUMMARY
+                    - name: STAGING_AI_SUMMARY
                       valueFrom:
                         secretKeyRef:
                           key: ai-summary
@@ -222,19 +156,13 @@ jobs:
                         port: 8080
                       initialDelaySeconds: 15
                       periodSeconds: 5
-                    livenessProbe:
-                      httpGet:
-                        path: /api/test/health
-                        port: 8080
-                      initialDelaySeconds: 30
-                      periodSeconds: 10
           EOF
           fi
 
       - name: Check current deployment
         id: check-deployment
         run: |
-          CURRENT_VERSION=$(kubectl get service ai-pro-server-service -o jsonpath='{.spec.selector.version}')
+          CURRENT_VERSION=$(kubectl get service ai-pro-staging-service -o jsonpath='{.spec.selector.version}')
           if [ "$CURRENT_VERSION" = "blue" ]; then
           echo "::set-output name=new_version::green"
           echo "::set-output name=current_version::blue"
@@ -247,42 +175,43 @@ jobs:
         env:
           NEW_VERSION: ${{ steps.check-deployment.outputs.new_version }}
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          echo "ECR REGISTRY: $ECR_REGISTRY"
         run: |
           cat <<EOF | kubectl apply -f -
           apiVersion: apps/v1
           kind: Deployment
           metadata:
-            name: ai-pro-server-${NEW_VERSION}
+            name: ai-pro-staging-${NEW_VERSION}
           spec:
             replicas: 2
             selector:
                matchLabels:
-                 app: ai-pro-server
+                 app: ai-pro-staging
                  version: ${NEW_VERSION}
             template:
              metadata:
                labels:
-                 app: ai-pro-server
+                 app: ai-pro-staging
                  version: ${NEW_VERSION}
              spec:
                containers:
-               - name: ai-pro-server
+               - name: ai-pro-staging
                  image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8080
                  env:
-                 - name: DB_URL
+                 - name: STAGING_DB_URL
                    valueFrom:
                      secretKeyRef:
                        key: db-url
                        name: db-config
-                 - name: DB_USERNAME
+                 - name: STAGING_DB_USERNAME
                    valueFrom:
                      secretKeyRef:
                        key: db-username
                        name: db-config
-                 - name: DB_PASSWORD
+                 - name: STAGING_DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: db-password
@@ -292,7 +221,7 @@ jobs:
                      secretKeyRef:
                        key: jwt-secret
                        name: app-config
-                 - name: AI_URL
+                 - name: STAGING_AI_URL
                    valueFrom:
                      secretKeyRef:
                        key: ai-url
@@ -303,48 +232,42 @@ jobs:
                      port: 8080
                    initialDelaySeconds: 15
                    periodSeconds: 5
-                 livenessProbe:
-                   httpGet:
-                     path: /api/test/health
-                     port: 8080
-                   initialDelaySeconds: 30
-                   periodSeconds: 10
           EOF
       - name: Wait for deployment
         env:
           NEW_VERSION: ${{ steps.check-deployment.outputs.new_version }}
         run: |
-          kubectl rollout status deployment/ai-pro-server-${NEW_VERSION} --timeout=300s
+          kubectl rollout status deployment/ai-pro-staging-${NEW_VERSION} --timeout=120s
 
-      - name: Verify deployment
-        env:
-          NEW_VERSION: ${{ steps.check-deployment.outputs.new_version }}
-        run: |
-          echo "Checking pod status..."
-          kubectl get pods -l version=${NEW_VERSION}
+      # - name: Verify deployment
+      #   env:
+      #     NEW_VERSION: ${{ steps.check-deployment.outputs.new_version }}
+      #   run: |
+      #     echo "Checking pod status..."
+      #     kubectl get pods -l version=${NEW_VERSION}
           
-          echo "Performing health checks..."
-          NEW_POD=$(kubectl get pods -l version=${NEW_VERSION} -o jsonpath='{.items[0].metadata.name}')
+      #     echo "Performing health checks..."
+      #     NEW_POD=$(kubectl get pods -l version=${NEW_VERSION} -o jsonpath='{.items[0].metadata.name}')
           
-          kubectl port-forward $NEW_POD 8080:8080 &
-          PF_PID=$!
-          sleep 5
+      #     kubectl port-forward $NEW_POD 8080:8080 &
+      #     PF_PID=$!
+      #     sleep 5
           
-          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/test/health)
-          kill $PF_PID
+      #     HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/test/health)
+      #     kill $PF_PID
           
-          if [ "$HEALTH_STATUS" != "200" ]; then
-            echo "Health check failed"
-            exit 1
-          fi
-          echo "Health check passed"
+      #     if [ "$HEALTH_STATUS" != "200" ]; then
+      #       echo "Health check failed"
+      #       exit 1
+      #     fi
+      #     echo "Health check passed"
 
       - name: Switch traffic
         if: success()
         env:
           NEW_VERSION: ${{ steps.check-deployment.outputs.new_version }}
         run: |
-          kubectl patch service ai-pro-server-service -p "{\"spec\":{\"selector\":{\"version\":\"${NEW_VERSION}\"}}}"
+          kubectl patch service ai-pro-staging-service -p "{\"spec\":{\"selector\":{\"version\":\"${NEW_VERSION}\"}}}"
           echo "Traffic switched to ${NEW_VERSION} version"
         
       - name: Monitor deployment
@@ -362,14 +285,14 @@ jobs:
           END_TIME=$((SECONDS + MONITORING_DURATION))
           
           while [ $SECONDS -lt $END_TIME ]; do
-            SERVICE_IP=$(kubectl get service ai-pro-server-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+            SERVICE_IP=$(kubectl get service ai-pro-staging-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
             echo "SERVICE_IP: $SERVICE_IP"
 
             if [ -z "$SERVICE_IP" ]; then
               echo "SERVICE_IP is empty. Using fallback URL."
             fi
             
-            RESPONSE=$(curl -s -w "\n%{http_code}" https://sinjjanggu.site/api/test/rollback)
+            RESPONSE=$(curl -s -w "\n%{http_code}" http(s)://xxx/api/test/rollback)
             HTTP_CODE=$(echo "$RESPONSE" | tail -n 1)
             HTTP_BODY=$(echo "$RESPONSE" | head -n -1)
             
@@ -387,8 +310,8 @@ jobs:
                 echo "Last failed response code: $HTTP_CODE"
                 echo "Last failed response body: $HTTP_BODY"
                 
-                kubectl patch service ai-pro-server-service -p "{\"spec\":{\"selector\":{\"version\":\"${CURRENT_VERSION}\"}}}"
-                kubectl delete deployment ai-pro-server-${NEW_VERSION}
+                kubectl patch service ai-pro-staging-service -p "{\"spec\":{\"selector\":{\"version\":\"${CURRENT_VERSION}\"}}}"
+                kubectl delete deployment ai-pro-staging-${NEW_VERSION}
                 
                 echo "Checking pods after rollback:"
                 kubectl get pods -l version=${CURRENT_VERSION}
@@ -415,7 +338,7 @@ jobs:
         env:
           CURRENT_VERSION: ${{ steps.check-deployment.outputs.current_version }}
         run: |
-          kubectl delete deployment ai-pro-server-${CURRENT_VERSION}
+          kubectl delete deployment ai-pro-staging-${CURRENT_VERSION}
           echo "Old deployment cleaned up"
   
       - name: Notify deployment status
